from django.urls import path
from  vasoraapp import views


urlpatterns = [    
    
    path('',views.index,name='index'),
    path('ex',views.ex,name='ex'),
    path('products',views.products,name='products'),
    path('product_details/<slug:slug>/', views.product_details, name='product_details'),
    path('cart/',views.cart,name='cart'),
    path('signup',views.signup,name='signup'),
    path('login',views.login,name='login'),
    path('usercreate',views.usercreate,name='usercreate'),
    path('signin',views.signin,name='signin'),
    path('logout_view',views.logout_view,name='logout_view'),
    path('admin_page',views.admin_page,name='admin_page'),
    path('contact_us',views.contact_us,name='contact_us'),
    path('contact_view',views.contact_view,name='contact_view'),
    path('message_list_view',views.message_list_view,name='message_list_view'),
    path('delete_message/<int:pk>/',views.delete_message,name='delete_message'),
    path('add_category_view',views.add_category_view,name='add_category_view'),
    path('edit_category_view/<int:category_id>/',views.edit_category_view,name='edit_category_view'),
    path('delete_category/<int:pk>/',views.delete_category,name='delete_category'),
    path('add_product',views.add_product,name='add_product'),
    path('edit_product/<int:product_id>/',views.edit_product,name='edit_product'),
    path('p_delete_form/<int:pk>/',views.p_delete_form,name='p_delete_form'),
    path('add_to_cart/<int:product_id>/',views.add_to_cart,name='add_to_cart'),
    path('update_cart_quantity',views.update_cart_quantity,name='update_cart_quantity'),
    path('remove_cart_item',views.remove_cart_item,name='remove_cart_item'),
    path('category_products/<int:category_id>/',views.category_products,name='category_products'),
    path('mark_trending',views.mark_trending,name='mark_trending'),
    path('trending_products',views.trending_products,name='trending_products'),
    path('delete_trending_product/<int:product_id>/',views.delete_trending_product,name='delete_trending_product'),
    path('add_to_wishlist/<int:product_id>/',views.add_to_wishlist,name='add_to_wishlist'),
    path('remove_from_wishlist/<int:product_id>/',views.remove_from_wishlist,name='remove_from_wishlist'),
    path('wishlist',views.wishlist,name='wishlist'),
    path('checkout',views.checkout,name='checkout'),
    path('process_order',views.process_order,name='process_order'),
    path('user_orders',views.user_orders,name='user_orders'),
    path('manage_orders',views.manage_orders,name='manage_orders'),
    path('update_order_status/<int:order_id>/',views.update_order_status,name='update_order_status'),
    path('search_results',views.search_results,name='search_results'),
    path('about_us',views.about_us,name='about_us'),
    path('add_testimonial_view',views.add_testimonial_view,name='add_testimonial_view'),
    path('edit_testimonial_view/<int:testimonial_id>/',views.edit_testimonial_view,name='edit_testimonial_view'),
    path('delete_testimonial/<int:testimonial_id>/',views.delete_testimonial,name='delete_testimonial'),
    path('order_success',views.order_success,name='order_success'),
    path('order_failure',views.order_failure,name='order_failure'),
    path('payment-callback/', views.payment_callback, name='payment_callback'),
    path('terms_and_condition',views.terms_and_condition,name='terms_and_condition'),
]