# Generated by Django 4.2.5 on 2024-08-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vasoraapp', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
            ],
        ),
    ]
