# Generated by Django 4.2.5 on 2024-08-13 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vasoraapp', '0004_product_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
    ]
