# Generated by Django 4.2.5 on 2024-08-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vasoraapp', '0009_customer_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
    ]
