# Generated by Django 4.2.5 on 2024-08-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vasoraapp', '0011_order_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='testimonials/')),
                ('testimonial_text', models.TextField()),
            ],
        ),
    ]
